# Generated by Django 3.1.3 on 2020-12-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketch',
            options={'verbose_name_plural': 'Sketches'},
        ),
    ]
