# Generated by Django 3.1.3 on 2021-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='status',
            field=models.CharField(choices=[('select', 'Select'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Denied', max_length=20),
        ),
    ]
