# Generated by Django 3.1.3 on 2021-01-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_sketch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketch',
            name='status',
        ),
    ]
