# Generated by Django 3.1.3 on 2020-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
