# Generated by Django 3.1.3 on 2020-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designcategory',
            options={'verbose_name_plural': 'Design Categories'},
        ),
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=6),
        ),
    ]
