# Generated by Django 3.1.3 on 2021-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sketch_name', models.CharField(max_length=254)),
                ('sketch_sku', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('special_requests', models.TextField()),
            ],
        ),
    ]
